# Setup
title:        FrontEnd and DataScience memo
tagline:      個人開発関連のブログとメモ
baseurl:      ""
paginate:     1
locale:       "ja"

# About/contact
author:
  name:       aki-mia
  url:        https://twitter.com/aki_honmono

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown